services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 256mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5555:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

